### ISSUE TITLE
Can we install it on RedHat?

### ISSUE THREAD

**Issue by khaled-rahman** [intel/intel-graphics-compiler#144]
Hi,
I was trying to build it on RedHat. I see the following error message with cmake:

```
 [VC] Cannot find SPIRVDLL sources in .../intel-graphics-compiler-igc-1.0.4427/IGC/VectorCompiler/../../../llvm-project/llvm/projects/llvm-spirv
CMake Error at IGC/VectorCompiler/cmake/spirv.cmake:75 (message):
  [VC] Cannot find SPIRVDLL sources in
  .../intel-graphics-compiler-igc-1.0.4427/IGC/VectorCompiler/../../../llvm-spirv
Call Stack (most recent call first):
  IGC/VectorCompiler/CMakeLists.txt:152 (include)
```

What could be a possible reason for this? Any suggestions or solutions?

**Comment by aarontcopal2** [comment]
Can someone comment on this? We too wanted to install igc on our redhat system. But the build instructions are only for ubuntu

**Comment by eero-t** [comment]
You do need to have the listed dependencies present.  Either install them sources, or use distro packages.

If you e.g. want to use disto (LLVM) SPIRV like the above error message indicates,  give -DINSTALL_SPIRVDLL=0 option to CMake (that's what I'm doing on Ubuntu).

PS. It seems that several of the deps can be skipped if you disable Vector Compiler (-DIGC_BUILD__VC_ENABLED=OFF), but that doesn't seem to be otherwise as well supported as building with it (see #143).

**Comment by agrachiv** [comment]
Hello.

It looks like, you didn't locate your sources properly. Please, follow the given [instruction](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md) for Ubuntu build.

**Comment by kvladimi** [comment]
Andrey meant please follow it for RedHat build. Then looks like this works, closing.
