### ISSUE TITLE
Remove common_clang dependency

### ISSUE THREAD

**Issue by chivakker** [intel/intel-graphics-compiler#53]
Please make sure that this dependency is fully removed for all versions of clang if possible.  If only a newer version will be able to remove this dependency please clarify.

**Comment by dvrogozh** [comment]
If I understand correctly common_clang is an IGC dependency. For example, see the grep:
```
# fgrep -rsn common_clang
IGC/OCLFE/igd_fcl_mcl/headers/clang_tb.h:38:#include "common_clang.h"
IGC/OCLFE/igd_fcl_mcl/headers/clang_tb.h:75:    // we rename the libcommon_clang.so. While the change is not introduced
IGC/OCLFE/igd_fcl_mcl/headers/clang_tb.h:87:      pModuleName = "common_clang64.dll";
IGC/OCLFE/igd_fcl_mcl/headers/clang_tb.h:90:      pModuleName = "common_clang32.dll";
IGC/OCLFE/igd_fcl_mcl/headers/clang_tb.h:93:      pModuleOldName = "libcommon_clang.so";
IGC/OCLFE/igd_fcl_mcl/source/clang_tb.cpp:28:#include "../headers/common_clang.h"
IGC/OCLFE/igd_fcl_mcl/source/clang_tb.cpp:615:                                          CCModule.pModule = dlopen("/usr/local/lib/libcommon_clang.so", RTLD_NOW);
```

However, I believe that IGC project can consider to detect common_clang installed on the system rather than build sources on its own. As I show in #54 and pr-#55 it is actually possible with the pretty minimal IGC build system modifications.

Somewhat confusing part around common_clang is that it provides .h and .so files, but it does not provide .pc file which would be optimal to detect it on the system. Should that be a bug against common_clang?

**Comment by chivakker** [comment]
Do @paigeale or you know if common_clang has to be installed as a library with a ABI/API or is it to be installed just as a plugin with no pc file?  I need to check @dvrogozh PR to try to mimic the same setup here and provide further comments.

**Comment by paigeale** [comment]
Validated with Author that this can be closed.
